name: server
version: 0.1.0.0
github: "nghiemduongkhai/Haskell-Game"
license: MIT
author: "nghiemduongkhai"
extra-source-files:
  - static/index.html

# ========= Library =========
library:
  source-dirs: src
  exposed-modules:
    - Game.Types
    - Game.State
    - Game.Logic
    - Game.Update
    - Network.WebSocket
    - Network.API
    - Utils.Config
    - Utils.Logging
  dependencies:
    - base >= 4.7 && < 5
    - aeson
    - bytestring
    - text
    - containers
    - websockets
    - async
    - parallel
    - time
    - directory
    - filepath
    - mtl
    - unordered-containers
    - stm

# ========= Executable =========
executables:
  server-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base
      - server        
    hs-source-dirs:
      - app
    default-language: Haskell2010

# ========= Tests =========
tests:
  server-test:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - base
      - server
      - hspec
    default-language: Haskell2010